Repository pivotal-cf/pcf-pipelines, pull requests merged in 2018-03, with the labels that each got.

#293 Make it match concourse-deployment manifest
  docs/samples/concourse-with-credhub.yml
Labels: unscheduled

#306 changed references from concourse.ci -> concourse-ci.org
  README.md
  docs/credhub-integration.md
  docs/vault-integration.md
  install-pcf/aws/README.md
  install-pcf/gcp/README.md
  install-pcf/openstack/README.md
  install-pcf/vsphere/README.md
  upgrade-ops-manager/vsphere/README.md
  upgrade-tile/README.md
  vendor/github.com/concourse/atc/README.md
  vendor/github.com/concourse/atc/atccmd/command.go
Labels: scheduled

#305 Updated param descriptions.
  install-pcf/azure/params.yml
Labels: unscheduled

#308 improving comment for secrets
  install-pcf/vsphere/params.yml
Labels: unscheduled

#287 Updated help in params.yml & errands in bootstrap
  ci/bootstrap/aws/tasks/bootstrap.sh
  install-pcf/aws/params.yml
  install-pcf/gcp/params.yml
  install-pcf/vsphere/params.yml
Labels: in progress
